/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as CrossrigRouteImport } from './routes/crossrig'
import { Route as BeadsRouteImport } from './routes/beads'
import { Route as IndexRouteImport } from './routes/index'
import { Route as ResultsIdRouteImport } from './routes/results.$id'
import { Route as FormulaNameRouteImport } from './routes/formula.$name'

const CrossrigRoute = CrossrigRouteImport.update({
  id: '/crossrig',
  path: '/crossrig',
  getParentRoute: () => rootRouteImport,
} as any)
const BeadsRoute = BeadsRouteImport.update({
  id: '/beads',
  path: '/beads',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const ResultsIdRoute = ResultsIdRouteImport.update({
  id: '/results/$id',
  path: '/results/$id',
  getParentRoute: () => rootRouteImport,
} as any)
const FormulaNameRoute = FormulaNameRouteImport.update({
  id: '/formula/$name',
  path: '/formula/$name',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/beads': typeof BeadsRoute
  '/crossrig': typeof CrossrigRoute
  '/formula/$name': typeof FormulaNameRoute
  '/results/$id': typeof ResultsIdRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/beads': typeof BeadsRoute
  '/crossrig': typeof CrossrigRoute
  '/formula/$name': typeof FormulaNameRoute
  '/results/$id': typeof ResultsIdRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/beads': typeof BeadsRoute
  '/crossrig': typeof CrossrigRoute
  '/formula/$name': typeof FormulaNameRoute
  '/results/$id': typeof ResultsIdRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths: '/' | '/beads' | '/crossrig' | '/formula/$name' | '/results/$id'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/beads' | '/crossrig' | '/formula/$name' | '/results/$id'
  id:
    | '__root__'
    | '/'
    | '/beads'
    | '/crossrig'
    | '/formula/$name'
    | '/results/$id'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  BeadsRoute: typeof BeadsRoute
  CrossrigRoute: typeof CrossrigRoute
  FormulaNameRoute: typeof FormulaNameRoute
  ResultsIdRoute: typeof ResultsIdRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/crossrig': {
      id: '/crossrig'
      path: '/crossrig'
      fullPath: '/crossrig'
      preLoaderRoute: typeof CrossrigRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/beads': {
      id: '/beads'
      path: '/beads'
      fullPath: '/beads'
      preLoaderRoute: typeof BeadsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/results/$id': {
      id: '/results/$id'
      path: '/results/$id'
      fullPath: '/results/$id'
      preLoaderRoute: typeof ResultsIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/formula/$name': {
      id: '/formula/$name'
      path: '/formula/$name'
      fullPath: '/formula/$name'
      preLoaderRoute: typeof FormulaNameRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  BeadsRoute: BeadsRoute,
  CrossrigRoute: CrossrigRoute,
  FormulaNameRoute: FormulaNameRoute,
  ResultsIdRoute: ResultsIdRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
